services:
  - type: web
    name: google-calendar-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_server.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
