// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZBidGKJk2W43kxHcYiCiWsc4opc8yzYw',
    appId: '1:250760656932:web:8f4fd43c1402f1c9f200b1',
    messagingSenderId: '250760656932',
    projectId: 'tesis-59cbb',
    authDomain: 'tesis-59cbb.firebaseapp.com',
    storageBucket: 'tesis-59cbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8_8BOaTXnpWGZ7p86z07ZVelEpBhTJX8',
    appId: '1:250760656932:android:d568b4b5b8902e6ef200b1',
    messagingSenderId: '250760656932',
    projectId: 'tesis-59cbb',
    storageBucket: 'tesis-59cbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgfPkAYwzScm05KEG0lU0jfxUMRqM6Z8A',
    appId: '1:250760656932:ios:58a3dfad64adf115f200b1',
    messagingSenderId: '250760656932',
    projectId: 'tesis-59cbb',
    storageBucket: 'tesis-59cbb.firebasestorage.app',
    iosBundleId: 'com.example.tesis',
  );
}
